names:
- cavidade
- levantamento_pavimento
- poda
- raiz_exposta
nc: 4
path: C:\Users\n1-arthur.oliveira\Documents\code\treerisk-ml\ml\projeto_arvores\dataset
test: images/teste
train: images/treino
val: images/validacao
